#!/usr/bin/env bash
# ==============================================================================================
# A remote find, based on zabbix agent vfs.dir.get key
# This script essentially offer a more convenient and usual interface to this key capability
# 
# A typical scenario is to provide a way to investigate remote files, without having access
# to the remote host (and without 'superpower' such as allowed system.run)
#
# Output is voluntarily kept as json (the output of the vfs.dir.get key), to be pretty 
# printed by tools such as jq, mlr, ...
# 
# Author : Stéphane Perrot 	(C) 2023 
#
# ----------------------------------------------------------------------------------------------
# TODO:
#
# DONE (sort of) Implement -ls (as in similish)
# ==============================================================================================
# For test default target

ip=""
TRACE=""
 
VERSION="0.7a (14-04-2026)"
 
PROGNAME=$(basename $0)
 
#TRACE=on
TRACE=""

# From (my script) similish
JQ_LL_EXTRACTOR="{type:.type, perms:.permissions, user:.user, group:.group, size:.size, datetime:.time.change, name:.basename}"

# From tabulate help, there are actually more recent format supported
# set output table format; supported formats:
#                           plain, simple, grid, fancy_grid, pipe, orgtbl,
#                           rst, mediawiki, html, latex, latex_raw,
#                           latex_booktabs, latex_longtable, tsv
#                           (default: simple)
GRID_STYLE=simple

# ==============================================================================================
# Section fonctions ...

# +TODO TO BE DEFINED
function check_prerequisites {
  :
}

function usage {
   cat <<EOF
 
     $PROGNAME: usage:
 
     $PROGNAME -ip ip -from topdir [-type f|d|l ] [-mtime -/+ ndays] [-size +10m] [-name pattern] [-ls] [-grid-style pattern]
 
     $PROGNAME -h|--help

     $PROGNAME -V|--version
 
     find equivalent, based on the new possibilities of zbx.dir.get key in Zabbix Agent (v6.0)
     -exec is not generally implementable
 
     outputs json, or text tabulated output when -ls is specified (-grid-style allows one to slightly modify output format (see tabulate(1))

     same goes to -exec grep ... : better left to an external utility
 
EOF
}
 
function show_version {
   echo "$PROGNAME: $VERSION"
}
 
# Input: 10k or 10M or 10G
# Output: value mult by multiplier
# NB : the leading + or - is not expected ...
function get_actual_value {
 
  tmp=$1
 
  value=${tmp%[MGk]*}
  case $tmp in
     *k) multiplier=1000 ;;
     *M) multiplier=1000000 ;;
     *G) multiplier=1000000000 ;;
     *)  multiplier=1 ;;
  esac
  ((actual_value = value * multiplier))
 
  echo $actual_value
}

# ==============================================================================================
# Section main ...
 
# Variables de travail pour l'appel zabbix_get
dir=""
 
regex_incl=""
regex_excl=""
 
#file,dir,sym,sock,bdev,cdev,fifo". Multiple types must be separated with comma and quoted.
 
types_incl=""
types_excl=""
 
max_depth=""

min_size=""
max_size=""
 
min_age=""
max_age=""
 
regex_excl_dir=""

# ----------------------------------------------------------------------------------------------
 
[[ -n $TRACE ]] && set -x
 
while [[ $# -ge 1 ]]
do
  opt=$1
  case $opt in
 
   -h|--help)		usage;          exit 0 ;;
   -V|--version)	show_version;   exit 0 ;;
 
   -from|-dir)		dir=$2;  	shift ;;
 
   -host|-ip)  		ip=$2;   	shift ;;
 
   -exec)		echo "-exec option not implemented yet, exiting..."; exit 9 ;;
 
   -grid-style )	GRID_STYLE=$2;  shift ;;

   -ls)			DO_LS=yes ;;
       
   -mtime)
        arg=$2
        case $arg in
          +*) value=${arg##*+}; (( min_age = value * 86400 )) ;;
          -*) value=${arg##*-}; (( max_age = value * 86400 )) ;;
        esac
 
        shift ;;
 
   -maxdepth)
        arg=$2; max_depth=$arg
        shift ;;
 
   -name) # for now ...
        arg=$2; regex_incl="$2"
        #echo "rexexp_incl='$regex_incl'"
        shift ;;
 
   -notname) # for now ...
        arg=$2; cl="$2"
        echo "rexexp_excl='$regex_excl'"
        shift ;;

   -size) # TODO: handle k, M or G suffix  !!
        arg=$2
        #echo "option=-size arg=$arg"
        case $arg in # presumed in k for now
          +*) tmp=${arg##*+}
              min_size=$(get_actual_value $tmp);
              ;;
          -*) tmp=${arg##*-};
              max_size=$(get_actual_value $tmp);
              ;;
        esac
        [[ ! -z $TRACE ]] && echo "max_size=$max_size  min_size=$min_size"
 
        shift ;;
 
   #file,dir,sym,sock,bdev,cdev,fifo". Multiple types must be separated with comma and quoted.
   #FIXME: handle multiple types together...
   -type)
        arg=$2
        case $arg in
          f) 	types_incl="file" ;;
          d) 	types_incl="dir"  ;;
          l) 	types_incl="sym"  ;;
          s) 	types_incl="sock" ;;
          b) 	types_incl="bdev" ;;
          c) 	types_incl="cdev" ;;
          ff) 	types_incl="fifo" ;;
	  *) echo "${PROGNAME}: unknown option: '$arg'..." 
        esac
 
        shift ;;
 
    *)   echo "option non supportee : $opt" ;;
 
  esac
 
  shift
done

#echo "ip=$ip dir=$dir ..."
[[ -z $ip  ]] && echo "ERROR: target (ip-or-host) must be specified, exiting..."            && exit 2
[[ -z $dir ]] && echo "ERROR: top directory must be specified (ex: -dir /opt)), exiting..." && exit 3

# FIXME: handle this in check_prerequisites
zabbix_get 2>&1 >/dev/null
rc=$? # 1 if present, 127 otherwise
case $rc in
  1)   : ;;
  127) echo "zabbix_get not available on this host, exiting ..."; exit 8;;
esac
 
version=$(zabbix_get -s "$ip" -k "agent.version")
 
case $version in
   [6789].*)    : ;;
   *)           echo "Remote agent is not sufficiently recent (actual version: ${version}, minimum version: v6.0)..." && exit 4;;
esac

# FIXME: better handle duplication ... (eval ?)
if [[ -z $DO_LS ]] ; then
    
    zabbix_get -s "$ip" -k "vfs.dir.get[${dir},${regex_incl},${regex_excl},${types_incl},${types_excl},${max_depth},${min_size},${max_size},${min_age},${max_age},${regex_excl_dir}]"

else

    zabbix_get -s "$ip" -k "vfs.dir.get[${dir},${regex_incl},${regex_excl},${types_incl},${types_excl},${max_depth},${min_size},${max_size},${min_age},${max_age},${regex_excl_dir}]" | jq -cMr ".[] | $JQ_LL_EXTRACTOR" | mlr --j2t cat | tabulate -1 -f ${GRID_STYLE}

fi


